### ISSUE TITLE
"Garbage in" vandamál, tengt opnun [ og lokun ], rouge lokun ]

### ISSUE THREAD

**Issue by Loknar** [althingi-net/lagasafn-xml#7]
get ekki sagt að ég sé búinn að digga djúpt í þennan kóða, en þegar ég prófaði að keyra `./lagasafn-xml -a` for funsies feilar það á eftirfarandi:

```
[   1/1645] Processing law nr. 134/1995...cleaning...making XML...failed
Traceback (most recent call last):
  File "./lagasafn-xml", line 2085, in process_law
    make_xml(law_num, law_year)
  File "./lagasafn-xml", line 1552, in make_xml
    started_at = opening_locations.pop()
IndexError: pop from empty list
```

og fari maður að skoða html-ið sem verið er að parsa á þessum tímapunkti í keyrslunni

```
<span id="G19A"></span><IMG SRC="sk.jpg" HEIGHT=11 WIDTH=11 alt=""> <b>[19. gr. a.</b><br><IMG SRC="hk.jpg" HEIGHT=11 WIDTH=11 alt="" id="G19AM1"> Ákvarðanir sem teknar eru á grundvelli laga þessara sæta kæru til úrskurðarnefndar umhverfis- og auðlindamála. Ákvörðun verður ekki borin undir dómstóla fyrr en úrskurður nefndarinnar liggur fyrir. Ef aðili unir ekki úrskurði nefndarinnar getur hann höfðað mál til ógildingar fyrir dómstólum. Höfða skal mál innan sex mánaða frá því að aðili fékk vitneskju um úrskurð nefndarinnar. Málshöfðun frestar ekki gildistöku úrskurðar nefndarinnar eða heimild til aðfarar. Um aðild, kærufrest, málsmeðferð og annað er varðar kæruna fer að öðru leyti samkvæmt lögum um úrskurðarnefnd umhverfis- og auðlindamála.]<sup style="font-size:60%">1)</sup>]<sup style="font-size:60%">2)</sup>
```

þá smáblasir við sýnist mér að það kemur einfaldlega rouge ] sem hefur ekkert [

nú veit ég ekkert hversu algengt þetta er, en ef þetta kemur iðulega fyrir, hvernig hljómar eftirfarandi lausn?

halda utanum síðustu opnun [ þegar opening_locations er pop tæmdur, fallback-a á að nota það til að loka rouge lokun ] komi hún upp, og nóta/logga einhverskonar warning um "garbage in" fallback vilji maður skoða hvort fallbackið hafi verið ásættanleg meðhöndlun?

edit: önnur hugmynd væri að reyna að taka einhverja "educated guess" ákvörðun um að gera ráð fyrir opnun [ í upphafi málsgreinar ef seinasta opnun sem lokað var er of langt í burtu ... eða eitthvað í þá áttina

**Comment by helgihg** [comment]
Athugaðu hina valkostina, -e og -E.

Til að keyra í gegnum allt lagasafnið, skrifandi niður villur í `errormap.json` og sýnandi upplýsingar um hversu mikið er af hvaða vilum, gerirðu:

    ./lagasafn -a -e -E

Sem þýðir: „Farðu í gegnum allt lagasafnið, skrifaðu niður villurnar og sýndu mér þær síðan.“

Ef þú nærð í nýjustu útgáfuna (sem ég var að henda upp rétt í þessu), og keyrir bara:

    ./lagasafn -E

Þá færðu lista yfir allar parsing villurnar sem voru til staðar þegar ég upphalaði seinustu útgáfunni. Þú þarft sumsé ekkert endilega að keyra í gegnum lagasafnið til að sjá þær.

Í útgáfu 151b var bara 1 svona villa eftir. Með útgáfau 151c hafa hinsvegar tvær nýjar bæst við, ásamt þremur af annarri tegund sem ég á eftir að skoða.

Ástæðan fyrir því að þetta gerist er einmitt eins og þú segir, að það gleymist að setja inn opnunar-hornklofa. Ég hef verið að senda þessi mál á tiltekinn aðila hjá Alþingi sem hefur þá lagað vandamálin í næstu útgáfu, enda mikill metnaður hjá Alþingi fyrir því að hafa þetta rétt. En þetta er tímafrekt ferli vegna þess að það þarf alltaf að bíða eftir næstu útgáfu Alþingis, sem kemur út kannski tvisvar-þrisvar sinnum á ári eða svo.

Ég er satt best að segja í svolitlum vandræðum með hvernig sé best að eiga við þetta. Mér hefur dottið í hug að hreinlega fletta upp sjálfur í lögunum hvar mistökin eru, því það er hægt að finna út úr því handvirkt (og bara handvirkt) hvar opnunar-hornklofinn eigi að vera, og búa til nýja mistaka-skrá (sem héti þá sennilega bara `input-mistakes.json` eða eitthvað svoleiðis), sem ritið myndi fletta upp í sjálfkrafa, ef það rekst á lokunar-hornklofa sem vantar opnunar-hornklofa.

Það væri reyndar alls ekki það ósnyrtilegasta sem ég hef þurft að gera til að eiga við allskonar sértilfelli.

Þessa virkni væri þá einnig hægt að láta senda sjálfkrafa póst á tilheyrandi aðila á Alþingi þegar þetta kemur upp, þannig að hægt sé að laga villuna í næstu útgáfu lagasafnsins. Með þeirri aðferð ætti þessi mistaka-skrá að geta verið bundin við hverja útgáfu lagasafnsins (jafnvel bara heita `input-mistakes.151c.json`, sem dæmi), sem myndi þýða að þær myndu fyrnast með tímanum og hægt væri að eyða þeim þegar þeirra er ekki þörf lengur. Það þyrfti þá bara að setja þetta inn handvirkt við hvert þing, en eftir allar lagfæringarnar sem hafa verið gerðar síðustu ár, þá ættu þetta aldrei að vera fleiri en 1-5 villur í hverri útgáfu. Sumsé, mjög auðveldlega meðfærilegt af sjálfboðaliða 2-3 sinnum á ári.

Þetta er eiginlega það snyrtilegasta sem mér dettur í hug til að eiga við þetta vandamál. Það er óhjákvæmilegt að þetta komi upp af og til, vegna þess að þessi skjöl eru útbúin af manneskjum og lagabreytingarnar geta verið mjög flóknar, sérstaklega í viðamiklum safnlögum (a.k.a. bandormar) þar sem er verið að breyta rosalega mörgum litlum hlutum í rosalega stórum lögum sem er þegar búið að breyta margsinnis. Mjög dæmigert er að þar sem þegar sé opnunar-hornklofi, gleymist að setja annan, þegar einhverju er breytt aftur.

Ef þig langar bara að klára parsing þrátt fyrir þessa villu, þá myndi ég mæla með því að þegar þú rekist á lokunar-hornklofa sem vantar opnunar-hornklofa, að hreinlega sleppa því að taka upp þá tilteknu breytinguna, þ.e. hunsa lokunarhornklofann. Ég er ekki alveg viss um hvort það skemmi eitthvað sem kemur síðar, en ég held að það sé einfaldasta svarið þar til eitthvað fágaðara er tilkomið.

Mér líst ekkert á að reyna einhverja ágiskun. Það er engin leið að giska á þetta með einhverjum vitrænum hætti. Betra væri að sleppa því að taka breytinguna með, og ennþá betra ef það væri þá merkt í XML-ið að það væri vitað að breytingu vantaði.

Vonandi er þetta allt skiljanlegt sem ég er að segja. Ekki vera feiminn við að spyrja. Þetta er algert kraðak og ég veit ekki alveg hversu samdauna ég er orðinn þessu. :)

**Comment by Loknar** [comment]
> satt best að segja í svolitlum vandræðum með hvernig sé best að eiga við þetta [..] dottið í hug að hreinlega fletta upp sjálfur í lögunum hvar mistökin eru [..] finna [mistökin] handvirkt

já, ég er satt að segja sammála núna, þ.e. að fallback-ágiskanir eins og sú sem ég stakk uppá séu óheppilegar, lagasafnið á betra skilið / parsed lagasafn má ekki vera meira garbage en orginalinn :smirk: 

okei, er með hugmynd(ir)

 1. [auka / nitpick] það sökkar feitt að skrárnar séu á Western (Windows 1252) / iso-8859-1 encoding, svona allskonar encodings fer í taugarnar á mér, unicode all the way! :laughing: hef svosem reynslu að vinna með allsskonar encodings en þegar ég hef fengið að ráða þá hef ég bara convertað skrám yfir í utf-8, það er bara að mínu mati langþægilegast,
 2. ef pælingin er að útbúa mistaka-skrá til að tækla garbage inn vandamál eins og þetta væri held ég sniðugast að koma upp diff/patch kerfi, sé fyrir mér að fyrir hverja lagasafns útgáfu værum við með möppurnar `orginal` með upprunalega windowns encodinginu (til öryggis?), `unicode` með utf-8 encoded files, `patch` möppu sem innihéldi samnefndar .patch skrár á -U0 (eða --unidiff-zero) formatti og loks `patched` möppu þar sem patchaðar skrár úr `unicode` og `patch` (eða afritaðar ef ekkert patch?) eru skrifaðar. Þá væri hægt að tækla öll svona garbage in vandamál án þess að littera python kóðann með sértilfellum. Ef þér hryllir við að hafa 3 útgáfur af sömu skránni þá væri hægt að setja `unicode` og `patched` möppurnar í gitignore og make-a þær möppur bara í keyrslu?

hvernig finnst þér diff/patch hugmyndin?

**ath:** smá leiðindi að diff/patch tólin eru ekki í standard lib og þau 3rd party libs sem ég hef séð í boði á pypi er ég ekki alveg öruggur með, varðandi trust á maintainer oþh, en það er í raun ekki stórmál að smíða bara diff/patch tólin, sjá t.d. https://gist.github.com/noporpoise/16e731849eb1231e86d78f9dfeca3abc, held að það væri öruggast að umrita / hafa til hliðsjónar / beturumbæta / gera meira readable þessa linkuðu skriptu og hafa í einhverri `diff-patch-utils.py` skrá, frekar en að pulla 3rd party modúl af pypi sem god-knows-who maintainar :sweat_smile: 

ef þér líst á þetta þá er ég geim í að græja svona `diff-patch-utils.py` skrá við tækifæri, en svo væri svosem líka hægt að nota einfaldlega GNU skipanalínutólin diff og patch og sleppa python impl

**Comment by helgihg** [comment]
# Diff-patch
Diff-patch hugmyndin er frábær. Ég er búinn að hringlast með miklu flóknari lausn í kollinum í mjög langan tíma núna.

Ég held þá að prinsippið sé best svona: Ef vandinn er þess eðlis að:
1. það verði að breyta inntakinu til að laga,
2. búast megi við því að Alþingi lagi vandann ef það fréttir af honum,
3. er ekki hluti af sniðinu sem Alþingi notar

að þá notum við diff-patch.

Við skulum bara passa að lenda ekki í scope-creep með það, vegna þess að við verðum að gera ráð fyrir því að þetta verði áfram í þessu gamla sniði þar sem er allskonar rugl í gangi sem er gert ráð fyrir í kóðanum. Líttu til dæmis á línu `lagasafn-xml.py:964` sem fjallar um `special_roman`. Alþingi er alveg til í að laga hrein mistök, en mjög oft eru gallarnir ekki mistök hjá skrifstofu Alþingis við að skrásetja, heldur kemur ýmist með frumvarpinu sem er samþykkt í þingsal, eða er hluti af uppsetningunni sem Alþingi hefur notað og við verðum að gera ráð fyrir að verði áfram notuð.

Annars ákvað ég líka í byrjun að hafa þetta ekkert háheilagt. Þetta er og verður áfram drullumall og meira eða minna samansafn af misgáfulegum skítmixum. Það er svolítið eðli verkefnisins.

En allavega, frábær hugmynd til að leysa þetta með hornklofana. Ef þú vilt reyna fyrir þér í þessu hef ég ekki sterkar skoðanir á því hvort þú notir PyPi pakka eða afritir kóða og aðlagir eða hvaðeina. Það eina sem mér er annt um er að kóðinn sé vel og mikið kommentaður, því eins og ég segi, þetta er í eðli sínu óskiljanlegt drullumall.

# Stafkóðun

Í `lagasafn-xml:49` sérðu að ég er búinn að kommenta afkóðunina sem var áður úr ISO-8859-1. Mér sýnist Python 3 bara gera þetta sjálfkrafa. Þannig að ISO-8859-1 hefur ekkert þvælst fyrir mér síðan þá. Ég sé í sjálfu sér enga ástæðu til að breyta stafkóðuninni á HTML/SGML skránum, en auðvitað verða XML skrárnar að vera í UTF-8, eins og þær eru. Þannig að mér finnst ekkert eftir þar að laga.

# Fleiri útgáfur af skránum

Það eru nú þegar þrjár útgáfur í ferlinu.
1. Fyrsta er HTML/SGML-ið hrátt frá Alþingi, sem ekkert er búið að gera við.
2. Önnur er hreinsuð HTML útgáfa, sem fer í möppuna `cleaned`. Þetta millistig er til þess að gera það auðveldara og fyrirsjáanlegra að vinna með textann. Það er þessi útgáfa sem forritið parsar síðan, ekki upprunalegu skrárnar. Þær eru í UTF-8 nú þegar og hvert tag er í einni línu. Þannig getur forritið litið í kringum sig og spurt með öruggum hætti hvað sé í þarnæstu línu, hvort að eitthvað kom á undan sem útskýrir samhengi o.s.frv. (Sjá `utils.superiter`, og hvernig hann er notaður í kóðanum.)
3. Þriðja útgáfan eru XML-skrárnar.

Það er mér algerlega að meinalausu að bæta við eins mörgum skrefum og þarf. Ég sé þetta þá fyrir mér þannig, miðað við það sem þú ert að lýsa, að það séu skrárnar í möppunum `151c` sem er upprunalega, síðan `patched` mappa þar sem er búið að bæta við pötchum fyrir hornklofana (og e.t.v. annað sem uppfyllir sömu skilyrði), `cleaned` sem er búið að fara í gegnum BeautifulSoup afvötnun og síðan `xml` með lokaútgáfunni.

Það eina sem skiptir mig máli hvað varðar stíl og vinnubrögð er að það sé sem skiljanlegast hvað sé í gangi, sem næst einna helst fram með því að kommenta vel og hressilega. Að öðru leyti er ég bara afar þakklátur ef einhver nennir að krukka í þessu fyrir utan sjálfan mig.

**Comment by Loknar** [comment]
[uppkast að diff_patch_utils.py skrá](https://gist.github.com/Loknar/dba2e05a4474e713fb5df9eaf572a6e1), vantar í þetta sýnist mér að tékka hvort lína áður en henni er breytt rími við hvað er í .patch skránni, held að það sé rétt að hafa slíkt tékk, annars gæti það ruglað í manni ef patch skráin endar uppi með rangt fyrir state for some reason, skoða að bæta því við þegar ég hef tíma

**Comment by Loknar** [comment]
gaf mér tíma í að fínisera diff_patch_utils, er að vinna í að skella í pullu með diff/patch feature, kemur vonandi í kvöld

**Comment by helgihg** [comment]
Geggjað stöff. Takk kærlega fyrir þetta. :)

**Comment by Kjarrval** [comment]
Ein hugmynd varðandi langa ferlið er að fá ritstjórn lagasafnsins tól sem athugar helstu villurnar, eins og þessa, og leggja til að þau keyri það á skránum áður en þau opinbera nýja útgáfu. Þá gætu þau fengið tækifæri til lagfæringa áður en skaðinn er skeður.
